// data.js
const collegeData = [
    // --- GERMANY ---
    {
        name: "Freie Universität Berlin",
        country: "Germany",
        city: "Berlin",
        type: "Public Research University",
        founded: 1948,
        language: "German & English",
        tuition: "~€350/sem",
        acceptanceRate: "45%",
        students: "35,000+",
        intlStudents: "21%",
        qsRank: "#98",
        monthlyCost: "€1,200",
        programs: ["Political Science", "History", "Biology", "Law", "Computer Science"],
        topEmployers: ["Siemens", "BMW", "German Government", "Zalando"],
        description: "One of Germany's premier research institutions, known for its strong focus on humanities, social sciences, and natural sciences. Located in the culturally vibrant capital, it offers a highly international environment and free tuition for all students.",
        rating: 4.6
    },
    {
        name: "Technical University of Munich (TUM)",
        country: "Germany",
        city: "Munich",
        type: "Public Technical University",
        founded: 1868,
        language: "English & German",
        tuition: "~€150/sem",
        acceptanceRate: "8%",
        students: "50,000+",
        intlStudents: "38%",
        qsRank: "#37",
        monthlyCost: "€1,500",
        programs: ["Aerospace Engineering", "Computer Science", "Physics", "Medicine", "Robotics"],
        topEmployers: ["BMW", "Audi", "Siemens", "Airbus", "Google"],
        description: "Consistently ranked as the #1 university in Germany. TUM is an elite hub for engineering, technology, and innovation, producing numerous Nobel laureates and leading industry professionals.",
        rating: 4.9
    },
    {
        name: "Ludwig Maximilian University of Munich",
        country: "Germany",
        city: "Munich",
        type: "Public Research University",
        founded: 1472,
        language: "German & English",
        tuition: "~€150/sem",
        acceptanceRate: "10%",
        students: "52,000+",
        intlStudents: "18%",
        qsRank: "#54",
        monthlyCost: "€1,500",
        programs: ["Humanities", "Law", "Economics", "Natural Sciences", "Medicine"],
        topEmployers: ["Allianz", "Munich Re", "McKinsey", "Max Planck Institutes"],
        description: "One of Europe's oldest and most prestigious universities. LMU offers a vast array of disciplines and boasts a historic campus right in the heart of Munich.",
        rating: 4.8
    },
    {
        name: "Heidelberg University",
        country: "Germany",
        city: "Heidelberg",
        type: "Public Research University",
        founded: 1386,
        language: "German & English",
        tuition: "~€170/sem",
        acceptanceRate: "15%",
        students: "28,000+",
        intlStudents: "20%",
        qsRank: "#87",
        monthlyCost: "€1,100",
        programs: ["Medicine", "Life Sciences", "Philosophy", "Physics", "Astronomy"],
        topEmployers: ["Bayer", "BASF", "SAP", "German Cancer Research Center"],
        description: "Germany's oldest university. Heidelberg is globally renowned for its medical school, life sciences research, and picturesque historic student town.",
        rating: 4.7
    },
    {
        name: "RWTH Aachen University",
        country: "Germany",
        city: "Aachen",
        type: "Public Technical University",
        founded: 1870,
        language: "German & English",
        tuition: "~€310/sem",
        acceptanceRate: "10%",
        students: "47,000+",
        intlStudents: "28%",
        qsRank: "#106",
        monthlyCost: "€950",
        programs: ["Mechanical Engineering", "Materials Science", "AI", "Automotive"],
        topEmployers: ["Porsche", "Bosch", "Daimler", "Ford"],
        description: "The largest technical university in Germany, closely tied to industrial giants. It is a dream destination for anyone pursuing mechanical or automotive engineering.",
        rating: 4.6
    },
    {
        name: "Humboldt University of Berlin",
        country: "Germany",
        city: "Berlin",
        type: "Public Research University",
        founded: 1810,
        language: "German & English",
        tuition: "~€320/sem",
        acceptanceRate: "18%",
        students: "36,000+",
        intlStudents: "22%",
        qsRank: "#120",
        monthlyCost: "€1,200",
        programs: ["Arts & Humanities", "Neuroscience", "Social Sciences", "Mathematics"],
        topEmployers: ["Charité", "Deutsche Bank", "European Union", "Bayer"],
        description: "The 'Mother of all modern universities'. Known for pioneering the integration of teaching and research. Alumni include Albert Einstein and Karl Marx.",
        rating: 4.5
    },
    {
        name: "KIT, Karlsruhe Institute of Technology",
        country: "Germany",
        city: "Karlsruhe",
        type: "Public Research Institution",
        founded: 1825,
        language: "German & English",
        tuition: "~€1,500/sem (Non-EU)",
        acceptanceRate: "25%",
        students: "22,000+",
        intlStudents: "24%",
        qsRank: "#119",
        monthlyCost: "€900",
        programs: ["Engineering", "Informatics", "Natural Sciences", "Climate Research"],
        topEmployers: ["SAP", "Bosch", "IBM", "Siemens"],
        description: "A unique institution combining a national research center with a premier university. Excellent for computer science and renewable energy technologies.",
        rating: 4.5
    },
    {
        name: "TU Berlin",
        country: "Germany",
        city: "Berlin",
        type: "Public Technical University",
        founded: 1879,
        language: "German & English",
        tuition: "~€310/sem",
        acceptanceRate: "22%",
        students: "33,000+",
        intlStudents: "27%",
        qsRank: "#154",
        monthlyCost: "€1,200",
        programs: ["Civil Engineering", "Architecture", "Mathematics", "Urban Planning"],
        topEmployers: ["Deutsche Bahn", "Tesla", "Amazon", "Bayer"],
        description: "Located in the heart of Berlin's startup ecosystem. TU Berlin is highly regarded for its architecture, civil engineering, and entrepreneurship programs.",
        rating: 4.3
    },
    {
        name: "University of Hamburg",
        country: "Germany",
        city: "Hamburg",
        type: "Public Research University",
        founded: 1919,
        language: "German",
        tuition: "~€330/sem",
        acceptanceRate: "18%",
        students: "43,000+",
        intlStudents: "12%",
        qsRank: "#205",
        monthlyCost: "€1,300",
        programs: ["Media", "Business", "Climate Science", "Law"],
        topEmployers: ["Airbus", "Lufthansa", "Beiersdorf", "Unilever"],
        description: "The largest research and education institution in northern Germany, with major research clusters in climate, earth sciences, and manuscript cultures.",
        rating: 4.2
    },
    {
        name: "TU Dresden",
        country: "Germany",
        city: "Dresden",
        type: "Public Technical University",
        founded: 1828,
        language: "German & English",
        tuition: "~€280/sem",
        acceptanceRate: "40%",
        students: "30,000+",
        intlStudents: "17%",
        qsRank: "#246",
        monthlyCost: "€850",
        programs: ["Microelectronics", "Transportation", "Psychology", "Materials Science"],
        topEmployers: ["Infineon", "GlobalFoundries", "Volkswagen", "Fraunhofer"],
        description: "A University of Excellence located in 'Silicon Saxony'. It is highly respected for microelectronics and nanotechnologies, offering a very affordable cost of living.",
        rating: 4.4
    },
    {
        name: "University of Cologne",
        country: "Germany",
        city: "Cologne",
        type: "Public Research University",
        founded: 1388,
        language: "German",
        tuition: "~€300/sem",
        acceptanceRate: "15%",
        students: "48,000+",
        intlStudents: "10%",
        qsRank: "#268",
        monthlyCost: "€1,100",
        programs: ["Business Admin", "Economics", "Humanities", "Sociology"],
        topEmployers: ["Ford", "REWE Group", "Telekom", "KPMG"],
        description: "One of the largest universities in Germany. Famous for its Faculty of Management, Economics and Social Sciences which is highly targeted by corporate recruiters.",
        rating: 4.1
    },

    // --- IRELAND ---
    {
        name: "Trinity College Dublin",
        country: "Ireland",
        city: "Dublin",
        type: "Public Research University",
        founded: 1592,
        language: "English",
        tuition: "~€18,000/yr (Non-EU)",
        acceptanceRate: "33%",
        students: "19,000+",
        intlStudents: "28%",
        qsRank: "#81",
        monthlyCost: "€1,800",
        programs: ["English Literature", "History", "Medicine", "Computer Science", "Law"],
        topEmployers: ["Google", "Meta", "Intel", "Accenture", "PwC"],
        description: "Ireland's most prestigious university, holding a historic campus in central Dublin. World-renowned for literature, humanities, and an increasingly strong tech alumni network.",
        rating: 4.8
    },
    {
        name: "University College Dublin (UCD)",
        country: "Ireland",
        city: "Dublin",
        type: "Public Research University",
        founded: 1854,
        language: "English",
        tuition: "~€20,000/yr (Non-EU)",
        acceptanceRate: "30%",
        students: "33,000+",
        intlStudents: "25%",
        qsRank: "#171",
        monthlyCost: "€1,750",
        programs: ["Veterinary Science", "Business", "Architecture", "Engineering"],
        topEmployers: ["KPMG", "Deloitte", "Microsoft", "AIB", "Bank of Ireland"],
        description: "Ireland's largest and most globally engaged university. UCD's Smurfit Business School is triple-crown accredited and highly sought after worldwide.",
        rating: 4.7
    },
    {
        name: "University College Cork (UCC)",
        country: "Ireland",
        city: "Cork",
        type: "Public Research University",
        founded: 1845,
        language: "English",
        tuition: "~€14,000/yr (Non-EU)",
        acceptanceRate: "40%",
        students: "22,000+",
        intlStudents: "16%",
        qsRank: "#292",
        monthlyCost: "€1,300",
        programs: ["Food Science", "Pharmacy", "Law", "Nursing", "Biotech"],
        topEmployers: ["Apple", "Pfizer", "Boston Scientific", "Dell"],
        description: "Located in Ireland's pharmaceutical hub, UCC is a leader in food science, sustainability, and life sciences research with a beautiful, green campus.",
        rating: 4.6
    },
    {
        name: "University of Galway",
        country: "Ireland",
        city: "Galway",
        type: "Public Research University",
        founded: 1845,
        language: "English",
        tuition: "~€15,000/yr (Non-EU)",
        acceptanceRate: "45%",
        students: "18,000+",
        intlStudents: "17%",
        qsRank: "#289",
        monthlyCost: "€1,200",
        programs: ["Marine Science", "Biomedical Engineering", "Medicine", "Arts"],
        topEmployers: ["Medtronic", "Cisco", "EA Games", "HSE"],
        description: "Situated in the cultural heart of Ireland on the wild Atlantic coast. The university is a global powerhouse for biomedical engineering and marine biology.",
        rating: 4.5
    },
    {
        name: "Dublin City University (DCU)",
        country: "Ireland",
        city: "Dublin",
        type: "Public University",
        founded: 1989,
        language: "English",
        tuition: "~€14,000/yr (Non-EU)",
        acceptanceRate: "45%",
        students: "17,000+",
        intlStudents: "19%",
        qsRank: "#436",
        monthlyCost: "€1,700",
        programs: ["Journalism", "Computing", "Business", "Communications"],
        topEmployers: ["RTE", "Google", "Intel", "KPMG", "TikTok"],
        description: "Known as Ireland's 'University of Enterprise', DCU focuses heavily on employability, industry partnerships, and features the top journalism school in the country.",
        rating: 4.4
    },
    {
        name: "University of Limerick (UL)",
        country: "Ireland",
        city: "Limerick",
        type: "Public University",
        founded: 1972,
        language: "English",
        tuition: "~€13,000/yr (Non-EU)",
        acceptanceRate: "50%",
        students: "16,000+",
        intlStudents: "15%",
        qsRank: "#426",
        monthlyCost: "€1,100",
        programs: ["Equine Science", "Music", "Aeronautical Engineering", "Sports Science"],
        topEmployers: ["Regeneron", "Stryker", "Analog Devices", "Northern Trust"],
        description: "Home to Ireland's premier sports facilities and a massive cooperative education (internship) program that ensures very high graduate employment rates.",
        rating: 4.5
    },
    {
        name: "Technological University Dublin (TU Dublin)",
        country: "Ireland",
        city: "Dublin",
        type: "Public Technological University",
        founded: 2019,
        language: "English",
        tuition: "~€12,500/yr (Non-EU)",
        acceptanceRate: "55%",
        students: "28,000+",
        intlStudents: "12%",
        qsRank: "#801+",
        monthlyCost: "€1,650",
        programs: ["Culinary Arts", "Marketing", "Engineering", "Digital Media"],
        topEmployers: ["HubSpot", "Workday", "AWS", "Marriott"],
        description: "Ireland's first technological university. It offers a practical, hands-on approach to learning, with the country's leading programs in culinary arts and hospitality.",
        rating: 4.1
    },

    // --- AUSTRIA ---
    {
        name: "University of Vienna",
        country: "Austria",
        city: "Vienna",
        type: "Public Research University",
        founded: 1365,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "35%",
        students: "90,000+",
        intlStudents: "28%",
        qsRank: "#130",
        monthlyCost: "€1,200",
        programs: ["Philosophy", "Translation", "Molecular Biology", "Physics"],
        topEmployers: ["UN", "Austrian Government", "Erste Group", "OMV"],
        description: "The oldest university in the German-speaking world and one of the largest in Europe. It is the academic heart of Vienna, producing 21 Nobel Prize winners.",
        rating: 4.7
    },
    {
        name: "TU Wien (Technical University)",
        country: "Austria",
        city: "Vienna",
        type: "Public Technical University",
        founded: 1815,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "25%",
        students: "27,000+",
        intlStudents: "30%",
        qsRank: "#184",
        monthlyCost: "€1,200",
        programs: ["Architecture", "Civil Engineering", "Informatics", "Quantum Physics"],
        topEmployers: ["Siemens", "Bosch", "AIT", "Kapsch"],
        description: "Austria's premier engineering and computer science hub. It sits directly in the city center and maintains incredibly strong ties with European tech industries.",
        rating: 4.5
    },
    {
        name: "University of Innsbruck",
        country: "Austria",
        city: "Innsbruck",
        type: "Public Research University",
        founded: 1669,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "45%",
        students: "28,000+",
        intlStudents: "45%",
        qsRank: "#362",
        monthlyCost: "€1,100",
        programs: ["Mountain Research", "Quantum Physics", "Tourism", "Meteorology"],
        topEmployers: ["Swarovski", "Red Bull", "Austrian Academy of Sciences"],
        description: "Located in the Alps, it is world-renowned for mountain research, climate studies, and quantum physics. An incredible destination for outdoors enthusiasts.",
        rating: 4.6
    },
    {
        name: "Graz University of Technology",
        country: "Austria",
        city: "Graz",
        type: "Public Technical University",
        founded: 1811,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "40%",
        students: "13,000+",
        intlStudents: "21%",
        qsRank: "#421",
        monthlyCost: "€950",
        programs: ["Applied Science", "Technical Physics", "Biomedical Engineering"],
        topEmployers: ["Magna Steyr", "AVL", "Infineon", "Andritz"],
        description: "A major player in European automotive and aerospace engineering research. Graz is a very affordable, youthful student city.",
        rating: 4.4
    },
    {
        name: "WU Vienna (Economics & Business)",
        country: "Austria",
        city: "Vienna",
        type: "Public Business School",
        founded: 1898,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "28%",
        students: "21,000+",
        intlStudents: "26%",
        qsRank: "#75 (Business)",
        monthlyCost: "€1,250",
        programs: ["International Business", "Economics", "Finance", "Supply Chain"],
        topEmployers: ["McKinsey", "BCG", "Goldman Sachs", "Red Bull", "L'Oréal"],
        description: "One of Europe's largest and most prestigious business schools, boasting a stunning, ultra-modern campus and Triple-Crown accreditation.",
        rating: 4.8
    },
    {
        name: "BOKU - University of Natural Resources",
        country: "Austria",
        city: "Vienna",
        type: "Public Specialty University",
        founded: 1872,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "45%",
        students: "12,000+",
        intlStudents: "20%",
        qsRank: "#651",
        monthlyCost: "€1,150",
        programs: ["Forestry", "Biotechnology", "Agriculture", "Water Management"],
        topEmployers: ["Austrian Environmental Agency", "Agrana", "Lenzing"],
        description: "Also known as the 'University of Life'. BOKU is Europe's leading institution for sustainability, forestry, and environmental sciences.",
        rating: 4.5
    },
    {
        name: "Mozarteum University Salzburg",
        country: "Austria",
        city: "Salzburg",
        type: "Public Arts University",
        founded: 1841,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "15%",
        students: "1,700+",
        intlStudents: "55%",
        qsRank: "#30 (Music)",
        monthlyCost: "€1,100",
        programs: ["Music Performance", "Conducting", "Fine Arts", "Drama"],
        topEmployers: ["Vienna Philharmonic", "Global Orchestras", "Opera Houses"],
        description: "Located in the birthplace of Mozart, this elite conservatory is a holy grail for classical musicians and performing artists globally.",
        rating: 4.9
    },
    {
        name: "Johannes Kepler University Linz",
        country: "Austria",
        city: "Linz",
        type: "Public Research University",
        founded: 1966,
        language: "German & English",
        tuition: "~€750/sem (Non-EU)",
        acceptanceRate: "55%",
        students: "20,000+",
        intlStudents: "14%",
        qsRank: "#446",
        monthlyCost: "€900",
        programs: ["Mechatronics", "Sociology", "Law", "AI", "Business"],
        topEmployers: ["Voestalpine", "Borealis", "Siemens", "Kepler Uni Hospital"],
        description: "A young, dynamic campus university known for having the first Mechatronics program in the world and strong AI research institutes.",
        rating: 4.2
    }
];